Added functionality to obtain circuit IDs
NJnisarg/tor_project pull request #13
Opened 2019-12-14 09:27 UTC by suhasks123

### Design:

TOR specifications mention that using *random numbers* to achieve the functionality is the optimal method. This might be for security reasons. But for the scale of our implementation, generating circuit IDs by *incrementing a preset number* is a simpler and more effective way of avoiding circuit ID collisions.

2019-12-16 11:21 UTC, NJnisarg commented
@suhasks123 The master has diverged since you PR. Can you align it before we merge it?

2019-12-16 13:14 UTC, suhasks123 commented
> @suhasks123 The master has diverged since you PR. Can you align it before we merge it?

I resolved the merge conflicts

2020-01-04 10:56 UTC, arpi-r requested changes

2020-01-04 10:56 UTC, arpi-r commented on onion_proxy/main.py
> +	current_circ_id += 1
Instead of incrementing current_circ_id again, set it to circ_id

2020-01-04 11:19 UTC, NJnisarg commented on onion_proxy/main.py
> +	current_circ_id += 1
@suhasks123 Please use something like a class variable and only one variable. It should not be this hard.

2020-01-04 16:29 UTC, suhasks123 commented on onion_proxy/main.py
> +	current_circ_id += 1
@NJnisarg So basically remove the get_rand_circ_id() altogether from circuit.py?

2020-01-05 18:11 UTC, suhasks123 commented on onion_proxy/main.py
> +	current_circ_id += 1
@arpi-r I made the changes

2020-01-12 05:10 UTC, merged